version: '3.7'
services:
  postgres:
    image: postgres:13
    restart: on-failure
    ports:
      - 5432:5432
    expose:
      - "5432"
    volumes:
      - ./docker/volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: limals
      POSTGRES_PASSWORD: 9fgJYRt11rz8OfL6ftw3cnTU9Ccyb98CGuSWYaTfShwCUIUn0E0EUQHgfqyQSMEw

volumes:
  postgres:
    name: limals
